//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCC_ClientApp.WCFServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/FCC_RestService.Entity")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSTOMER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSTOMER_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LANG_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SUBSCRIPTION_TYPE_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                if ((this.CUSTOMER_IDField.Equals(value) != true)) {
                    this.CUSTOMER_IDField = value;
                    this.RaisePropertyChanged("CUSTOMER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMER_NAME {
            get {
                return this.CUSTOMER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSTOMER_NAMEField, value) != true)) {
                    this.CUSTOMER_NAMEField = value;
                    this.RaisePropertyChanged("CUSTOMER_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMER_NO {
            get {
                return this.CUSTOMER_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSTOMER_NOField, value) != true)) {
                    this.CUSTOMER_NOField = value;
                    this.RaisePropertyChanged("CUSTOMER_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIDField, value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LANG_CODE {
            get {
                return this.LANG_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.LANG_CODEField, value) != true)) {
                    this.LANG_CODEField = value;
                    this.RaisePropertyChanged("LANG_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((this.MobileField.Equals(value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SUBSCRIPTION_TYPE_ID {
            get {
                return this.SUBSCRIPTION_TYPE_IDField;
            }
            set {
                if ((this.SUBSCRIPTION_TYPE_IDField.Equals(value) != true)) {
                    this.SUBSCRIPTION_TYPE_IDField = value;
                    this.RaisePropertyChanged("SUBSCRIPTION_TYPE_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/FCC_RestService.Entity")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QUANTITYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVE {
            get {
                return this.ACTIVEField;
            }
            set {
                if ((this.ACTIVEField.Equals(value) != true)) {
                    this.ACTIVEField = value;
                    this.RaisePropertyChanged("ACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRODUCTID {
            get {
                return this.PRODUCTIDField;
            }
            set {
                if ((this.PRODUCTIDField.Equals(value) != true)) {
                    this.PRODUCTIDField = value;
                    this.RaisePropertyChanged("PRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCT_NAME {
            get {
                return this.PRODUCT_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_NAMEField, value) != true)) {
                    this.PRODUCT_NAMEField = value;
                    this.RaisePropertyChanged("PRODUCT_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCT_NO {
            get {
                return this.PRODUCT_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_NOField, value) != true)) {
                    this.PRODUCT_NOField = value;
                    this.RaisePropertyChanged("PRODUCT_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QUANTITY {
            get {
                return this.QUANTITYField;
            }
            set {
                if ((this.QUANTITYField.Equals(value) != true)) {
                    this.QUANTITYField = value;
                    this.RaisePropertyChanged("QUANTITY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer_Product", Namespace="http://schemas.datacontract.org/2004/07/FCC_RestService.Entity")]
    [System.SerializableAttribute()]
    public partial class Customer_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BALANCE_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BOUGHT_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_PRODUCT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRODUCTIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BALANCE_QTY {
            get {
                return this.BALANCE_QTYField;
            }
            set {
                if ((this.BALANCE_QTYField.Equals(value) != true)) {
                    this.BALANCE_QTYField = value;
                    this.RaisePropertyChanged("BALANCE_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BOUGHT_QTY {
            get {
                return this.BOUGHT_QTYField;
            }
            set {
                if ((this.BOUGHT_QTYField.Equals(value) != true)) {
                    this.BOUGHT_QTYField = value;
                    this.RaisePropertyChanged("BOUGHT_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                if ((this.CUSTOMER_IDField.Equals(value) != true)) {
                    this.CUSTOMER_IDField = value;
                    this.RaisePropertyChanged("CUSTOMER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_PRODUCT_ID {
            get {
                return this.CUSTOMER_PRODUCT_IDField;
            }
            set {
                if ((this.CUSTOMER_PRODUCT_IDField.Equals(value) != true)) {
                    this.CUSTOMER_PRODUCT_IDField = value;
                    this.RaisePropertyChanged("CUSTOMER_PRODUCT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRODUCTID {
            get {
                return this.PRODUCTIDField;
            }
            set {
                if ((this.PRODUCTIDField.Equals(value) != true)) {
                    this.PRODUCTIDField = value;
                    this.RaisePropertyChanged("PRODUCTID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Balance", Namespace="http://schemas.datacontract.org/2004/07/FCC_RestService.Entity")]
    [System.SerializableAttribute()]
    public partial class Balance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Balance_QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bought_QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Balance_Qty {
            get {
                return this.Balance_QtyField;
            }
            set {
                if ((this.Balance_QtyField.Equals(value) != true)) {
                    this.Balance_QtyField = value;
                    this.RaisePropertyChanged("Balance_Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bought_Qty {
            get {
                return this.Bought_QtyField;
            }
            set {
                if ((this.Bought_QtyField.Equals(value) != true)) {
                    this.Bought_QtyField = value;
                    this.RaisePropertyChanged("Bought_Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Name {
            get {
                return this.Customer_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_NameField, value) != true)) {
                    this.Customer_NameField = value;
                    this.RaisePropertyChanged("Customer_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_no {
            get {
                return this.Customer_noField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_noField, value) != true)) {
                    this.Customer_noField = value;
                    this.RaisePropertyChanged("Customer_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_No {
            get {
                return this.Product_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NoField, value) != true)) {
                    this.Product_NoField = value;
                    this.RaisePropertyChanged("Product_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustomer", ReplyAction="http://tempuri.org/IService1/GetAllCustomerResponse")]
        FCC_ClientApp.WCFServiceReference1.Customer[] GetAllCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCustomer", ReplyAction="http://tempuri.org/IService1/GetAllCustomerResponse")]
        System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Customer[]> GetAllCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        bool InsertCustomer(FCC_ClientApp.WCFServiceReference1.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        System.Threading.Tasks.Task<bool> InsertCustomerAsync(FCC_ClientApp.WCFServiceReference1.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        bool UpdateCustomer(FCC_ClientApp.WCFServiceReference1.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerAsync(FCC_ClientApp.WCFServiceReference1.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        bool DeleteCustomer(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerById", ReplyAction="http://tempuri.org/IService1/GetCustomerByIdResponse")]
        FCC_ClientApp.WCFServiceReference1.Customer[] GetCustomerById(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerById", ReplyAction="http://tempuri.org/IService1/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Customer[]> GetCustomerByIdAsync(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProduct", ReplyAction="http://tempuri.org/IService1/GetAllProductResponse")]
        FCC_ClientApp.WCFServiceReference1.Product[] GetAllProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProduct", ReplyAction="http://tempuri.org/IService1/GetAllProductResponse")]
        System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Product[]> GetAllProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProduct", ReplyAction="http://tempuri.org/IService1/InsertProductResponse")]
        bool InsertProduct(FCC_ClientApp.WCFServiceReference1.Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProduct", ReplyAction="http://tempuri.org/IService1/InsertProductResponse")]
        System.Threading.Tasks.Task<bool> InsertProductAsync(FCC_ClientApp.WCFServiceReference1.Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        bool UpdateProduct(FCC_ClientApp.WCFServiceReference1.Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(FCC_ClientApp.WCFServiceReference1.Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        bool DeleteProduct(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductById", ReplyAction="http://tempuri.org/IService1/GetProductByIdResponse")]
        FCC_ClientApp.WCFServiceReference1.Product[] GetProductById(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductById", ReplyAction="http://tempuri.org/IService1/GetProductByIdResponse")]
        System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Product[]> GetProductByIdAsync(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer_Product", ReplyAction="http://tempuri.org/IService1/InsertCustomer_ProductResponse")]
        bool InsertCustomer_Product(FCC_ClientApp.WCFServiceReference1.Customer_Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer_Product", ReplyAction="http://tempuri.org/IService1/InsertCustomer_ProductResponse")]
        System.Threading.Tasks.Task<bool> InsertCustomer_ProductAsync(FCC_ClientApp.WCFServiceReference1.Customer_Product c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalanceProduct", ReplyAction="http://tempuri.org/IService1/GetBalanceProductResponse")]
        FCC_ClientApp.WCFServiceReference1.Balance[] GetBalanceProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalanceProduct", ReplyAction="http://tempuri.org/IService1/GetBalanceProductResponse")]
        System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Balance[]> GetBalanceProductAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FCC_ClientApp.WCFServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FCC_ClientApp.WCFServiceReference1.IService1>, FCC_ClientApp.WCFServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FCC_ClientApp.WCFServiceReference1.Customer[] GetAllCustomer() {
            return base.Channel.GetAllCustomer();
        }
        
        public System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Customer[]> GetAllCustomerAsync() {
            return base.Channel.GetAllCustomerAsync();
        }
        
        public bool InsertCustomer(FCC_ClientApp.WCFServiceReference1.Customer c) {
            return base.Channel.InsertCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomerAsync(FCC_ClientApp.WCFServiceReference1.Customer c) {
            return base.Channel.InsertCustomerAsync(c);
        }
        
        public bool UpdateCustomer(FCC_ClientApp.WCFServiceReference1.Customer c) {
            return base.Channel.UpdateCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerAsync(FCC_ClientApp.WCFServiceReference1.Customer c) {
            return base.Channel.UpdateCustomerAsync(c);
        }
        
        public bool DeleteCustomer(int CustomerID) {
            return base.Channel.DeleteCustomer(CustomerID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int CustomerID) {
            return base.Channel.DeleteCustomerAsync(CustomerID);
        }
        
        public FCC_ClientApp.WCFServiceReference1.Customer[] GetCustomerById(int ProductID) {
            return base.Channel.GetCustomerById(ProductID);
        }
        
        public System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Customer[]> GetCustomerByIdAsync(int ProductID) {
            return base.Channel.GetCustomerByIdAsync(ProductID);
        }
        
        public FCC_ClientApp.WCFServiceReference1.Product[] GetAllProduct() {
            return base.Channel.GetAllProduct();
        }
        
        public System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Product[]> GetAllProductAsync() {
            return base.Channel.GetAllProductAsync();
        }
        
        public bool InsertProduct(FCC_ClientApp.WCFServiceReference1.Product c) {
            return base.Channel.InsertProduct(c);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductAsync(FCC_ClientApp.WCFServiceReference1.Product c) {
            return base.Channel.InsertProductAsync(c);
        }
        
        public bool UpdateProduct(FCC_ClientApp.WCFServiceReference1.Product c) {
            return base.Channel.UpdateProduct(c);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(FCC_ClientApp.WCFServiceReference1.Product c) {
            return base.Channel.UpdateProductAsync(c);
        }
        
        public bool DeleteProduct(int ProductID) {
            return base.Channel.DeleteProduct(ProductID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int ProductID) {
            return base.Channel.DeleteProductAsync(ProductID);
        }
        
        public FCC_ClientApp.WCFServiceReference1.Product[] GetProductById(int ProductID) {
            return base.Channel.GetProductById(ProductID);
        }
        
        public System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Product[]> GetProductByIdAsync(int ProductID) {
            return base.Channel.GetProductByIdAsync(ProductID);
        }
        
        public bool InsertCustomer_Product(FCC_ClientApp.WCFServiceReference1.Customer_Product c) {
            return base.Channel.InsertCustomer_Product(c);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomer_ProductAsync(FCC_ClientApp.WCFServiceReference1.Customer_Product c) {
            return base.Channel.InsertCustomer_ProductAsync(c);
        }
        
        public FCC_ClientApp.WCFServiceReference1.Balance[] GetBalanceProduct() {
            return base.Channel.GetBalanceProduct();
        }
        
        public System.Threading.Tasks.Task<FCC_ClientApp.WCFServiceReference1.Balance[]> GetBalanceProductAsync() {
            return base.Channel.GetBalanceProductAsync();
        }
    }
}
